### ISSUE TITLE
hacksaw is stripping the < from the body tag

### ISSUE THREAD

**Issue by joepagan** [ryanshrum/hacksaw#1]
I have absolutely no idea why, but, using this :
`<p>{{ firstNewsTextBlock.text|hacksaw(hack='words', limit='10', append="&hellip;") }}</p>`

results in this:

![image](https://cloud.githubusercontent.com/assets/2337910/22560556/f6716616-e96c-11e6-8b62-cd595411158d.png)

Changing the hack to characters behaves normally:
`<p>{{ firstNewsTextBlock.text|hacksaw(hack='characters', limit='10', append="&hellip;") }}</p>`

![image](https://cloud.githubusercontent.com/assets/2337910/22560586/15afdfd0-e96d-11e6-995e-a7ca8f7e3160.png)

Any ideas?

**Comment by ryanshrum** [comment]
I'm not really sure what's going on here with the screenshots, they're very cutoff. What is the expected result here?

**Comment by ryanshrum** [comment]
Disregard me previous, deleted comment. Can you send me the snippet via Slack or email that you're trying to work with so I can test and try to see what's happening where? Admittedly, I haven't tried it with `<html />` or `<body />` tags, let alone having script tags in there.

Happy to take a look.

**Comment by joepagan** [comment]
Just to confirm, I wasn't trying to output this body tags with hacksaw.

Think I have just figured out what this is... Do you remember the separate issue I once commented on about nbsp being replaced as weird characters? https://github.com/ehousestudio/craft_hacksaw/issues/16

Well, I think that was the cause:

![image](https://cloud.githubusercontent.com/assets/2337910/22892565/f968a9be-f20a-11e6-880e-473bbd26710e.png)

causes this:
![image](https://cloud.githubusercontent.com/assets/2337910/22892578/00c91db0-f20b-11e6-8dd5-245621f36299.png)

I've gone in the wysiwyg, deleted the nbsp, now it's gone & my body tag is ok

I think this may also be an issue with my local MAMP4 environment (I contacted craft about this once), I don't think I have seen these characters on a production server either.

**Comment by ryanshrum** [comment]
Ok, I'm going to close this for the time being. Of course, let me know if you run into anything again.

**Comment by joepagan** [comment]
Ok will do, would be good if you could update your version as show in that issue to deal with space characters better if possible? Not sure what this is causing it though. Do you have any ideas?
